# Generated by Django 2.2.4 on 2019-09-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_flight_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='first_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
