# Generated by Django 2.2.4 on 2019-09-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190910_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='distance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
