# Generated by Django 2.2.4 on 2019-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_account',
            field=models.CharField(max_length=30),
        ),
    ]
