# Generated by Django 2.2.4 on 2019-09-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_flight_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_order',
            name='user',
        ),
        migrations.AddField(
            model_name='flight_order',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
