# Generated by Django 2.2.4 on 2019-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190911_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_order',
            name='f_id',
            field=models.IntegerField(null=True),
        ),
    ]
