# Generated by Django 2.2.4 on 2019-09-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_flight_order_f_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_order',
            name='f_id',
        ),
    ]
