# Generated by Django 2.2.4 on 2019-09-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_flight_order_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
